jobs:
  include:
    - stage: deploy to staging
      script: skip
      deploy: &heroku
        provider: heroku
        app: fhv-frontend-staging
        api_key: $HEROKU_API_KEY
    - stage: automatic user acceptance tests on staging
      script:
        - cd ..
        - "git clone https://github.com/fhv-msi/sentiment-analysis-tests.git"
        - cd sentiment-analysis-tests
        - mvn verify
        - cd ..
        - "git clone https://github.com/fhv-msi/sentiment-analysis-docs.git"
        - rm -rf sentiment-analysis-docs/generated/cukedoctor sentiment-analysis-docs/generated/walk_through.mp4
        - cp -r sentiment-analysis-tests/target/cukedoctor sentiment-analysis-docs/generated/
        - cd sentiment-analysis-docs/generated
        - ../../sentiment-analysis-tests/scripts/get_testingbot_video.py
        - git add --all
        - git commit -am "update documentation"
        - git push "https://${TRAVIS_GITHUB_TOKEN}@github.com/fhv-msi/sentiment-analysis-docs.git" master
    - stage: deploy to production
      script: skip
      deploy:
        <<: *heroku
        app: fhv-frontend
    - stage: check production availability
      script: 'curl https://fhv-frontend.herokuapp.com/'
