jobs:
  include:
    - stage: deploy to staging
      script: skip
      deploy: &heroku
        provider: heroku
        app: fhv-frontend-staging
        api_key: $HEROKU_API_KEY
    - stage: automatic user acceptance tests on staging
      script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
        - cd ..
        - "git clone https://github.com/fhv-msi/sentiment-analysis-tests.git"
        - cd sentiment-analysis-tests
        - mvn verify
        - "cd ../sentiment-analysis-frontend"
    - stage: deploy to production
      script: skip
      deploy:
        <<: *heroku
        app: fhv-frontend
    - stage: check production availability
      script: 'curl https://fhv-frontend.herokuapp.com/'
